### ISSUE TITLE
No fields shown under entry tab, Call to member function save() on a non-object

### ISSUE THREAD

**Issue by bloveless** [anomalylabs/pages-module#14]
Trying to create a new page.

Steps:
- Fresh Install
- Create Field "Editor" named "Content"
- Create new page type "Default"
- Assign "Content" field to "Default" Page type
- Add New Page type "Default"

Under entry. "No fields available"

- Set page title to "Home"
- Click save

![screen shot 2015-06-30 at 9 51 33 am](https://cloud.githubusercontent.com/assets/535135/8435304/b8537d0e-1f0d-11e5-93b6-f6063ea0599a.png)

**Comment by bloveless** [comment]
I'm actually seeing this "Call to a member function save() on a non-object" in a few places.

**Comment by bloveless** [comment]
https://github.com/anomalylabs/streams-platform/blob/1.0/develop/src/Ui/Form/Command/SaveForm.php#L43

Here the $repository is null

**Comment by bloveless** [comment]
This also happens in the posts module when trying to create a new post.

**Comment by RyanThompson** [comment]
Check out the SetDefaultProperties command in the Table namespace - it should get the entry / model from the table / guessing and then it'll test if it's eloquent / entry / whatever.

**Comment by RyanThompson** [comment]
Ya it's going to be occurring early - should be in there. Ill look it up shortly.

**Comment by RyanThompson** [comment]
I take it back - should be in \Anomaly\Streams\Platform\Ui\Table\Command\SetTableRepository

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/streams-platform/commit/3788de393a45cb959d197bb3ccf839eae4368f61
