### ISSUE TITLE
Fields not show on new page form

### ISSUE THREAD

**Issue by j-hubb** [anomalylabs/pages-module#16]
http://d.pr/v/14wA6

**Comment by RyanThompson** [comment]
Composer update on this too - and let me know if it persists.

Be sure to run `composer clear-cache` first.

**Comment by RyanThompson** [comment]
Be sure to not only add the field but also add it to a page type.

![screen shot 2015-07-01 at 3 07 33 am](https://cloud.githubusercontent.com/assets/1099967/8450242/743be232-1f9e-11e5-9935-a1208446932f.png)

**Comment by j-hubb** [comment]
Yup, this is fixed now.

**Comment by RyanThompson** [comment]
Sweet


Ryan Thompson
President / CEO
AnomalyLabs, Inc.
www.anomaly.is<http://www.anomaly.is>

t (877) 705-0806
m (309) 752-8581



On Jul 1, 2015, at 1:39 PM, John Hubbard <notifications@github.com<mailto:notifications@github.com>> wrote:


Yup, this is fixed now.
