### ISSUE TITLE
Four content areas in pages module

### ISSUE THREAD

**Issue by bloveless** [anomalylabs/pages-module#17]
When translations are enabled.

![screencapture-control4-dev-admin-pages-edit-1-1435765511273](https://cloud.githubusercontent.com/assets/535135/8458755/03cca706-1fd6-11e5-9977-b79e1653fc54.png)

Also saving translatable content field type doesn't save content, but looks like it is saving something.

![screen shot 2015-07-01 at 9 45 44 am](https://cloud.githubusercontent.com/assets/535135/8458772/2077c8f4-1fd6-11e5-8b39-9c3990a55807.png)

**Comment by RyanThompson** [comment]
Is this the same across other field types?

**Comment by bloveless** [comment]
I did noticed that the title is not saving correctly.

**Comment by bloveless** [comment]
Wait. Nevermind. I didn't put different values in for that one.

**Comment by bloveless** [comment]
I'll add another field to the pages module and try it out

**Comment by RyanThompson** [comment]
is es-la in your locales?

**Comment by bloveless** [comment]
Yes

**Comment by RyanThompson** [comment]
Supported: https://github.com/anomalylabs/streams-platform/blob/1.0/develop/resources/config/locales.php

**Comment by bloveless** [comment]
I added it to the supported list as well.

**Comment by bloveless** [comment]
![screen shot 2015-07-01 at 9 53 39 am](https://cloud.githubusercontent.com/assets/535135/8458919/13026c96-1fd7-11e5-8dda-ec8324390713.png)

**Comment by RyanThompson** [comment]
No problems here..

![screen shot 2015-07-01 at 10 58 39 am](https://cloud.githubusercontent.com/assets/1099967/8459057/39f38f48-1fe0-11e5-9dcd-b78a5b818d08.png)

**Comment by RyanThompson** [comment]
Oops.. wait..

**Comment by bloveless** [comment]
Alright. I will go fresh again. Maybe I jacked something up somehow.

**Comment by RyanThompson** [comment]
No you didn't - Im on it.


Ryan Thompson
President / CEO
AnomalyLabs, Inc.
www.anomaly.is<http://www.anomaly.is>

t (877) 705-0806
m (309) 752-8581



On Jul 1, 2015, at 11:00 AM, bloveless <notifications@github.com<mailto:notifications@github.com>> wrote:


Alright. I will go fresh again. Maybe I jacked something up somehow.

**Comment by RyanThompson** [comment]
Try now: https://github.com/anomalylabs/streams-platform/commit/62f163870e8277e5bdd8b7dcd76119bd439d7056

**Comment by RyanThompson** [comment]
Im saving correctly too - reopen it it's still squirrelly!

**Comment by bloveless** [comment]
I'm still getting multiple editor fields.

![screen shot 2015-07-01 at 11 49 53 am](https://cloud.githubusercontent.com/assets/535135/8461105/61ebb0f0-1fe7-11e5-8fe2-fd260f6a917e.png)

They save correctly as long as I fill in the last content area, change to spanish and fill in the last content area again.

**Comment by RyanThompson** [comment]
Pull and fresh install and let me know if this is still there..

**Comment by bloveless** [comment]
This issue is still present.

**Comment by RyanThompson** [comment]
Let me know but this should be fixed now as well.

**Comment by bloveless** [comment]
Fixed.
