### ISSUE TITLE
Edit page gives unexpected result 

### ISSUE THREAD

**Issue by j-hubb** [anomalylabs/pages-module#2]
/admin/pages/edit/1 gives http://d.pr/i/1in7y

**Comment by RyanThompson** [comment]
Ya - this part I am still buttoning up - fixing soon (trying to decouple the request DATA from the form builder but.. eh.

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/pages-module/commit/2b33856b460fee7064f4609604f04d4e141ae1b9
