### ISSUE TITLE
Editing translatable pages doesn't populate current content

### ISSUE THREAD

**Issue by bloveless** [anomalylabs/pages-module#20]
DB has content

![screen shot 2015-07-01 at 2 23 11 pm](https://cloud.githubusercontent.com/assets/535135/8464058/b8dbc8e0-1ffc-11e5-8b5f-b99d7bc8c911.png)

Editor is not pre-populated

English

![screen shot 2015-07-01 at 2 23 53 pm](https://cloud.githubusercontent.com/assets/535135/8464075/d4b58b28-1ffc-11e5-84ad-54bfaa2a9a0f.png)

Or Spanish

![screen shot 2015-07-01 at 2 23 05 pm](https://cloud.githubusercontent.com/assets/535135/8464067/c4c1ba02-1ffc-11e5-913c-b6cfbf671272.png)

**Comment by RyanThompson** [comment]
This ons is tricky..

**Comment by RyanThompson** [comment]
Still working on this one.

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/streams-platform/commit/886c219488708c0bc6401999941137cfc539eed3

https://github.com/anomalylabs/editor-field_type/commit/07dde2598fb18990f0c00a09108a3896a9c89242

Can you try this now? Only the editor field type - If it works as expected, which it appears to, I will clean up and move the same logic to the other field types.
