### ISSUE TITLE
Translatable content in pages needs to be more than 255 characters

### ISSUE THREAD

**Issue by bloveless** [anomalylabs/pages-module#22]
![screen shot 2015-07-02 at 9 41 05 am](https://cloud.githubusercontent.com/assets/535135/8481084/7bc21be2-209e-11e5-8928-151ad227ecd6.png)

**Comment by bloveless** [comment]
The field type for this area is an editor field. I don't know if that matters.

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/editor-field_type/commit/7a2c0531611a11cc63f6ff0451496d857e2a5707
