### ISSUE TITLE
Page content doesn't make it through to the front end

### ISSUE THREAD

**Issue by bloveless** [anomalylabs/pages-module#23]
No content makes it through to the page

![screen shot 2015-07-02 at 9 44 53 am](https://cloud.githubusercontent.com/assets/535135/8481214/1fcf3120-209f-11e5-9697-ddcd8a766475.png)

Even though there is content in the database

![screen shot 2015-07-02 at 9 45 11 am](https://cloud.githubusercontent.com/assets/535135/8481218/239cc010-209f-11e5-9b6b-88378620ba80.png)

The layout has the h1 in it, and that makes it to the front.

![screen shot 2015-07-02 at 9 46 28 am](https://cloud.githubusercontent.com/assets/535135/8481239/4e9a9576-209f-11e5-9d61-07924b688a6a.png)

**Comment by bloveless** [comment]
This probably relates to https://github.com/anomalylabs/pages-module/issues/20

**Comment by RyanThompson** [comment]
Ya this is a duplicate - it's only related to the field types that dump to file.
