### ISSUE TITLE
Creating new page type causes duplicate key issue

### ISSUE THREAD

**Issue by jhubb-io** [anomalylabs/pages-module#32]
![screencapture-pyrocms-dev-admin-pages-types-create-1448900356418](https://cloud.githubusercontent.com/assets/6826637/11477088/293b6de0-977e-11e5-8519-91fe73ade338.png)

On every new page type at admin/pages/types/create

**Comment by j-hubb** [comment]
This seems to be fixed with the latest version 1.1.2
