### ISSUE TITLE
Setting a homepage messes with PostsModule routes

### ISSUE THREAD

**Issue by damian-pf** [anomalylabs/pages-module#37]
I have identified a very strange issue. It is caused by setting a page as the homepage. This bug (somehow) causes the posts to no longer use any post routes and EVERYTHING (404s, whatever isn’t a page) gets picked up by the catch-all route in the Pages Module and shows the (newly set) homepage. It is not a redirect as the URL stays intact.

**Comment by RyanThompson** [comment]
Hmm.. whats the output of php artisan route:list?
