### ISSUE TITLE
Allowed to add the same field twice

### ISSUE THREAD

**Issue by j-hubb** [anomalylabs/pages-module#4]
It's possible to add the same field to the same page type twice.

**Comment by j-hubb** [comment]
Subsequently, if you remove one of them, then the column is removed in the page type table but the field still shows in the page type admin, so you get a column not found error when trying to create a page.

**Comment by RyanThompson** [comment]
Ah this is a core issue then - good catch. Gotta make unique validation in the main table and in the form builder for assignments / fields.

**Comment by RyanThompson** [comment]
If you reinstall this is prevented in the database layer (along with some other preventions I added). 

I also tweaked the UI in the pages module to not provide the option to add an already assigned field.
