### ISSUE TITLE
Reorder not working on /admin/pages/types/fields/%

### ISSUE THREAD

**Issue by j-hubb** [anomalylabs/pages-module#5]

**Comment by RyanThompson** [comment]
click reorder at bottom when finished sorting?

**Comment by j-hubb** [comment]
Tried that already, but it refreshed without reordering.

http://d.pr/i/U6ZO

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/streams-platform/commit/5f89a5fe7e755ff409abff5dee37d5fde17f761f
