### ISSUE TITLE
Incorrect breadcrumb for settings

### ISSUE THREAD

**Issue by j-hubb** [anomalylabs/pages-module#6]
![screen shot 2015-05-15 at 09 27 40](https://cloud.githubusercontent.com/assets/6826637/7649417/b78eae04-fae4-11e4-82f5-ca133e4e4d3a.png)

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/settings-module/commit/c93e914526d8ba725c252142cc67dd28e28536ab
